- name: install | apt packages
  package:
    name:
      # basic stuff and dependencies
      - git
      - gh
      - curl
      - htop
      - tree
      - tmux
      - gnome-software-plugin-flatpak
      - ca-certificates
      - gnupg
      - lsb-release
      - dconf-cli
      - python3-psutil
      - python3-pip
      - laptop-mode-tools
      - gnome-tweaks
      - lm-sensors
      - gnome-shell-extension-autohidetopbar
      - gnome-shell-extension-prefs
      - ttf-mscorefonts-installer
      - default-jre
      - default-jdk
      - grub-customizer
      - baobab
      # dev stuff
      - docker-ce
      - docker-ce-cli
      - containerd.io
      # stuff i want
      - gnome-system-monitor
      - google-chrome-stable
      - qbittorrent
      - thunderbird
    state: latest
  register: packages
  until: packages is success
  retries: 10
  delay: 10

- name: install | snap packages
  community.general.snap:
    name:
      # utilities
      - notepad-plus-plus
      - obs-studio
      - onlyoffice-desktopeditors
      - jdownloader2
      - canonical-livepatch
      - p7zip-desktop
      - okular
      # dev stuff
      - org.gnome.Boxes
      # stuff I want
      - discord
    state: present

- name: install | snap packages classic
  community.general.snap:
    name:
      # dev stuff
      - code
      - android-studio
    classic: true
    state: present

- name: install | flatpak packages
  community.general.flatpak:
    name:
      # utilities
      - com.usebottles.bottles
      # design stuff
      - org.darktable.Darktable
      - com.rawtherapee.RawTherapee
      - org.kde.krita
      - org.gimp.GIMP
      - org.gimp.GIMP.Manual/x86_64/2.10
      - org.gimp.GIMP.Plugin.BIMP/x86_64/2-40
      - org.gimp.GIMP.Plugin.FocusBlur/x86_64/2-40
      - org.gimp.GIMP.Plugin.Fourier/x86_64/2-40
      - org.gimp.GIMP.Plugin.GMic/x86_64/2-40
      - org.gimp.GIMP.Plugin.Lensfun/x86_64/2-40
      - org.gimp.GIMP.Plugin.LiquidRescale/x86_64/2-40
      - org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-40
      # stuff I want
      - com.stremio.Stremio
      - org.videolan.VLC
      - com.calibre_ebook.calibre
      - com.dropbox.Client
    state: present


- name: install | pip packages
  pip:
    name:
      - docker-compose
      - speedtest-cli
    state: present

- name: install | install nvm
  become_user: '{{ user_login }}'
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: "/home/{{ user_login }}/.nvm/nvm.sh"
  register: nvm_install

- name: install | try to install lts node if possible
  become_user: '{{ user_login }}'
  block:
    - name: install | nvm | bash lts node
      shell: . "/home/{{ user_login }}/.nvm/nvm.sh" && nvm install --lts
      register: nvm_install_bash
  rescue:
    - name: install | nvm | bash debug
      debug:
        msg: "{{ nvm_install_bash.stdout | to_nice_json }}"
      when: nvm_install_bash.rc != 0
  when: nvm_install is success
