- import_tasks: roles/base/tasks/packages/steps/install/nvm.yml

# breaking up to avoid failing because of one missing package
- import_tasks: roles/base/tasks/packages/steps/install/apt.yml
- import_tasks: roles/base/tasks/packages/steps/install/snap.yml
- import_tasks: roles/base/tasks/packages/steps/install/flatpak.yml
- import_tasks: roles/base/tasks/packages/steps/install/pip.yml
