- name: base | configure ubuntu (packages, apps, setup, etc...)
  tags: install
  block:
    - import_tasks: roles/base/tasks/packages/main.yml
    - import_tasks: roles/base/tasks/services/example.yml
    - import_tasks: roles/base/tasks/ansible/setup.yml
  rescue:
    - set_fact: task_failed=true