- import_tasks: roles/base/tasks/packages/steps/repositories.yml
- import_tasks: roles/base/tasks/packages/steps/install.yml
- import_tasks: roles/base/tasks/packages/steps/oh-my-zsh.yml
- import_tasks: roles/base/tasks/packages/steps/dracula-terminal.yml
- import_tasks: roles/base/tasks/packages/steps/gnome-extensions.yml
- import_tasks: roles/base/tasks/packages/steps/ubuntu-drivers.yml