# packages
- import_tasks: roles/base/tasks/packages/steps/repositories.yml
- import_tasks: roles/base/tasks/packages/steps/install.yml
- import_tasks: roles/base/tasks/packages/steps/oh-my-zsh.yml
- import_tasks: roles/base/tasks/packages/steps/dracula-terminal.yml
- import_tasks: roles/base/tasks/packages/steps/gnome-extensions.yml
- import_tasks: roles/base/tasks/packages/steps/ubuntu-drivers.yml
# - import_tasks: roles/base/tasks/packages/steps/nordvpn.yml

# updater
- import_tasks: roles/base/tasks/packages/updates.yml


- name: dropbox
  become: true
  import_role:
    name: ansible-dropbox
  rescue:
    - set_fact: task_failed=true

- name: nordvpn
  become: true
  import_role:
    name: ansible-nordvpn
  vars:
    auto_connect: true
    auto_connect_host: "br"
    firewall: true
    kill_switch: true
    cyber_sec: true
    notifications: true
    technology: "NORDLYNX"
    login: false
    # username: my@email.com
    # password: "my passwd, preferable encrypted, see https://bit.ly/3rOIlz3"
  rescue:
    - set_fact: task_failed=true
