- name: packages | flatpak
  block:
    - name: repositories | add flatpak repo
      apt_repository:
        repo: ppa:flatpak/stable
        state: present

    - name: repositories | add flatpak
      apt:
        name: flatpak
        state: present
      register: flatpak

    - name: repositories | Add flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
      when: flatpak.changed

    - name: repositories | Add flathub flatpak repository
      shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      when: flatpak.changed

- name: install | flatpak packages
  block:
    - name: install | flatpak packages
      community.general.flatpak:
        name:
          # design stuff
          - org.darktable.Darktable
          # stuff I want
          - com.stremio.Stremio
          - org.videolan.VLC
          - org.qbittorrent.qBittorrent
          - com.dropbox.Client
          # dev stuff
          - org.gnome.Boxes
          # utilities
          # - com.usebottles.bottles
          # design stuff
          # - com.rawtherapee.RawTherapee
          # - org.kde.krita
          # - org.gimp.GIMP
          # - org.gimp.GIMP.Manual/x86_64/2.10
          # - org.gimp.GIMP.Plugin.BIMP/x86_64/2-40
          # - org.gimp.GIMP.Plugin.FocusBlur/x86_64/2-40
          # - org.gimp.GIMP.Plugin.Fourier/x86_64/2-40
          # - org.gimp.GIMP.Plugin.GMic/x86_64/2-40
          # - org.gimp.GIMP.Plugin.Lensfun/x86_64/2-40
          # - org.gimp.GIMP.Plugin.LiquidRescale/x86_64/2-40
          # - org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-40
          # stuff I want
          # - com.calibre_ebook.calibre
          # dev stuff
          # - org.gnome.Boxes
        state: present
  rescue:
    - set_fact: task_failed=true
